---
title: "de Bruin code"
format: html
editor: visual
---

```{r set-up}
library(sf)
library(terra)
```

```{r data-import}
deB_data <- "deBruin_2022/sytbru-CV-clustered-data-9f8bc10/data/"
deB_strata <- terra::vect(file.path(deB_data, "strata.shp"))
deB_mask <- terra::rast(file.path(deB_data, "TOTmask.tif"))

terra::crs(deB_strata) <- terra::crs(deB_mask)
```

-   strata files

```{r plot-sf-object}
library(ggplot2)
deB_strata_sf <- sf::st_as_sf(deB_strata)
## TODO; add column to sf showing overweighted ids
ggplot() + geom_sf(data = deB_strata_sf, aes())
dplyr::distinct(deB_strata, ID)
```

```{r}
plot(deB_mask)
```

### Generate clustered sample

```{r}

## data sampling parameters
n_strata <- 100               ## no. of spatial units
cluster_pct <- 0.2            ## no. of units in weighted clusters
n_cluster_strata <-           
  cluster_weight * n_strata
total_obs <- 5000             ## no. of available observational units

pct_sample_from_cluster <-    ## pct of 
  0.5

n_cluster_sample <- total_obs * pct_sample_from_cluster
n_other_sample <- total_obs - n_cluster_sample

```

``` r
## from de Bruin code

set.seed(1234567)

total_clusters <- 100
cluster_weight <- 0.2 * 100
cluster_sample_pct <- 0.5
n_obs <- 5000
n_cluster_sample <- n_obs * cluster_sample_pct
n_other_sample <- n_obs - n_cluster_sample

# 1st case: 50% sample from 20% of the area
for (i in 1:n_samp){
  ## CH: pick 20% of area
  idx <- sample.int(100, 20) ## total_clusters, cluster_weight
  ndx <- setdiff(1:100, idx)
  
  ## CH: raster mask matching weighted clusters
  msk1 <- mask(msk, strata[idx,])
  msk2 <- mask(msk, strata[ndx,])
  
  ## CH: msk1 -- weighted clusters; msk2 -- "unweighted" clusters
  sub <- sample(cells(msk1), 2500) ## n_cluster_sample
  sub <- c(sub, sample(cells(msk2), 2500)) # n_other_sample
  ## CH: readability imorovement
  # sub <- c(sample(cells(msk1), 2500), 
  #        sample(cells(msk2), 2500))
  pts <- xyFromCell(msk, sub)
  
  AGBdata <- extract(AGBstack, sub)
  OCSdata <- extract(OCSstack, sub)
  AGBdata$glc2017 <- factor(AGBdata$glc2017, levels=1:8)
  OCSdata$glc2017 <- factor(OCSdata$glc2017, levels=1:8)
  
  fname <- paste0("AGBdata", sprintf("%03d", i), ".Rdata")
  save(AGBdata, file=file.path(outfolder, "clusterMedium", fname))
  fname <- paste0("OCSdata", sprintf("%03d", i), ".Rdata")
  save(OCSdata, file=file.path(outfolder, "clusterMedium", fname))
}
```

### Attempt to create strata grid

```{r}

```
